// src/demo/react/App.tsx
import { useRef, useEffect, useState } from 'react';
import { useStore } from '../../react';
import { demoStore, TOTAL_CELLS } from '../store';

export const ReactCell = ({ index }: { index: number }) => {
  const state = useStore(demoStore);
  const cell = state.grid.cells[index];

  const renderCount = useRef(0);
  renderCount.current++;

  const [flash, setFlash] = useState(false);
  const prevValue = useRef(cell.value);

  useEffect(() => {
    if (cell.value !== prevValue.current) {
      setFlash(true);
      const t = setTimeout(() => setFlash(false), 400);
      prevValue.current = cell.value;
      return () => clearTimeout(t);
    }
  }, [cell.value]);

  const handleClick = () => {
    const target = demoStore.state.grid.cells[index];
    target.value++;
    target.hue = (target.hue + 25) % 360;
  };

  return (
    <div
      className={`cell-wrapper ${flash ? 'cell-flash' : ''}`}
      style={{ backgroundColor: `hsla(${cell.hue}, 70%, 35%, 0.8)` }}
      onClick={handleClick}
    >
      <span className="cell-render-badge">{renderCount.current}</span>
      <span className="cell-value">{cell.value}</span>
    </div>
  );
};

export const App = () => {
  const appRenderCount = useRef(0);
  appRenderCount.current++;

  const state = useStore(demoStore);
  const indices = useRef(Array.from({ length: TOTAL_CELLS }, (_, i) => i));

  return (
    <div className="panel panel-react">
      <div className="panel-header">
        <div className="panel-title">
          <span>React Application</span>
        </div>
        <span className="panel-badge">Panel Renders: {appRenderCount.current}</span>
      </div>

      <div className="matrix-grid">
        {indices.current.map((index) => (
          <ReactCell key={index} index={index} />
        ))}
      </div>

      <div className="widgets-row">
        <div className="widget-box">
          <span className="widget-label">Global Counter</span>
          <span className="widget-content">{state.count}</span>
          <button onClick={() => demoStore.state.count++}>+1 Count</button>
        </div>
        <div className="widget-box">
          <span className="widget-label">Time Sync</span>
          <span className="widget-content">{new Date(state.time).toLocaleTimeString()}</span>
        </div>
      </div>
    </div>
  );
};

// src/demo/lit/App.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { consumeStore } from '../../lit';
import { demoStore, TOTAL_CELLS } from '../store';

@customElement('lit-cell')
export class LitCell extends LitElement {
  @property({ type: Number })
  index!: number;

  @consumeStore(demoStore)
  state!: typeof demoStore.state;

  private renderCount = 0;
  private lastValue: number | undefined = undefined;
  private flash = false;

  createRenderRoot() {
    return this; // Render in Light DOM so global style.css applies seamlessly
  }

  render() {
    this.renderCount++;
    const cell = this.state.grid.cells[this.index];

    if (this.lastValue !== undefined && cell.value !== this.lastValue) {
      this.flash = true;
      setTimeout(() => {
        this.flash = false;
        this.requestUpdate();
      }, 400);
    }
    this.lastValue = cell.value;

    return html`
      <div
        class="cell-wrapper ${this.flash ? 'cell-flash' : ''}"
        style="background-color: hsla(${cell.hue}, 70%, 35%, 0.8)"
        @click="${this.handleClick}"
      >
        <span class="cell-render-badge">${this.renderCount}</span>
        <span class="cell-value">${cell.value}</span>
      </div>
    `;
  }

  private handleClick() {
    const target = demoStore.state.grid.cells[this.index];
    target.value++;
    target.hue = (target.hue + 25) % 360;
  }
}

@customElement('my-app')
export class App extends LitElement {
  @consumeStore(demoStore)
  state!: typeof demoStore.state;

  private appRenderCount = 0;

  createRenderRoot() {
    return this;
  }

  render() {
    this.appRenderCount++;
    const indices = Array.from({ length: TOTAL_CELLS }, (_, i) => i);

    return html`
      <div class="panel panel-lit">
        <div class="panel-header">
          <div class="panel-title">
            <span>Lit Application</span>
          </div>
          <span class="panel-badge"> Panel Renders: ${this.appRenderCount} </span>
        </div>

        <div class="matrix-grid">
          ${indices.map((index) => html`<lit-cell .index="${index}"></lit-cell>`)}
        </div>

        <div class="widgets-row">
          <div class="widget-box">
            <span class="widget-label">Global Counter</span>
            <span class="widget-content">${this.state.count}</span>
            <button @click="${() => demoStore.state.count++}">+1 Count</button>
          </div>
          <div class="widget-box">
            <span class="widget-label">Time Sync</span>
            <span class="widget-content"> ${new Date(this.state.time).toLocaleTimeString()} </span>
          </div>
        </div>
      </div>
    `;
  }
}
